### PR TITLE
Trigger 'playlistended' event on player when reaching the end of a playlist

### PR DESCRIPTION
**Pull request by Djules**
Useful if you want to loop on the playlist, doing something like this:

```javascript
player.on('playlistended', function() {
    // loop on playlist
    player.playlist.currentItem(0);
});
```

### CODE REVIEW

**Comment by gkatsev** [comment]
We've considered this before but thought that it isn't required yet to keep the code more minimal but also because a user of this plugin can tell whether we're at the end or not by listening to `ended` events and checking the index.
Is there a strong usecase to having a specific `playlistended` event other than being able to know when the playlist changes more easily?

**Comment by Djules** [comment]
You made a point.
Well, my need is to restart the playlist when last video ends, acting a a loop.

The issue is if I call again `playlist.currentItem(0)` on `ended` event, the playlist restart from index = 1, can't tell why this happens...

**Comment by gkatsev** [comment]
Huh, interesting. Can you open a separate issue for that?

**Comment by gkatsev** [comment]
A possible workaround would be to call `currentTime(0)` in a `setTimeout(0)`, probably.

**Comment by jefonseca** [comment]
> The issue is if I call again playlist.currentItem(0) on ended event, the playlist restart from index = 1, can't tell why this happens...

I think the problem with the `index = 1` is that you call `playlist.currentItem(0)` on the `ended` event, and then you call the `player.playlist.autoadvance` method, so it skips the first item on the playlist.

I use this 
`player.on('ended', function() {`
`	if (player.playlist.next() === undefined) {`
`		player.playlist.first(); }; ` 
`	});`
instead `player.playlist.autoadvance(0)` to  loop the playlist

**Comment by gkatsev** [comment]
Thanks for your interesting. While the PR is good, we're still not ready to support a `playlistended` event.

**Pull request closed without merging**
