### PR TITLE
Changing the sequence of properties on OR expression

### PR DESCRIPTION
**Pull request by vdeshpande**
Changing the sequence of how we are adding in the endTime , because we always want to have endTime evaluated first even when we have the property time.

### CODE REVIEW

**Comment by dmlap** [comment]
Can you add/update a test case to fail before this change and succeed after?

**Comment by vdeshpande** [comment]
@dmlap Added the test. Let me know if that test seems relevant.

**Comment by misteroneill** [comment]
Should this ordering be the case for `startTime` as well? That is: `cue.startTime || cue.time || 0`?

**Comment by vdeshpande** [comment]
@misteroneill We can order it to make it look aesthetically consistent code, but the ordering is not needed for `startTime` as we are not adding to or modifying `startTime` as we are doing for `endTime`

**Comment by misteroneill** [comment]
Sounds good. This LGTM then.

**Comment by gkatsev** [comment]
I still think that it would be good to make the change to move `startTime` to be first, if that's the new way of doing things. Plus it makes the code be consistent and more readable.
In addition, I think each argument should now be on a separate line rather than having startTime on the first line and endTime and type on the second.

**Comment by misteroneill** [comment]
That's a good point about consistency.

**Comment by gkatsev** [comment]
We should make the change but because it doesn't affect the functionality, there's no need to make a release of it just yet.

**Comment by misteroneill** [comment]
Just did it in `master` :cow:👦

**Comment by gkatsev** [comment]
tsk tsk :tongue:

**Pull request merged**
