### PR TITLE
Updates for VideoJS 5.0

### PR DESCRIPTION
**Pull request by misteroneill**
Brings this plugin up to date with VideoJS 5.0 API changes.

### CODE REVIEW

**Comment by dmlap** [comment]
Not bad at all! We may want to consider a "compatibility" script for 5.0 that `s/EventEmitter/EventTarget/g` to help people through the transition. LGTM.

**Comment by gkatsev** [comment]
I highly doubt that anyone other than me used the EventEmitter :)

**Comment by forbesjo** [comment]
We should probably make a dist branch for easy testing.

**Comment by misteroneill** [comment]
Agreed, will do.

**Pull request closed without merging**
